backend:
  name: git-gateway
  branch: master

media_folder: "assets/img"

collections:
  - name: "any"
    label: "any"
    folder: "assets/img"
    fields:
      - name: "any"
        required: false